- README.md
- package.json
- yarn.lock
- Update readme with min cli version
- Update package.json to min version
> Update cli to v1.15.0

- src/main/java/io/percy/appium/AppPercy.java
- src/main/java/io/percy/appium/providers/AppAutomate.java
- src/main/java/io/percy/appium/providers/GenericProvider.java
- src/test/java/io/percy/appium/providers/AppAutomateTest.java
- src/test/java/io/percy/appium/providers/GenericProviderTest.java
- src/test/java/io/percy/appium/providers/ProviderResolverTest.java
- update getsessionDetails method to not call BrowserStack executor
- Update tests
> update getSessionDetails method to not call browserstack executor

- src/main/java/io/percy/appium/lib/PercyOptions.java
Jira: https://browserstack.atlassian.net/browse/PAPP-65
> print warning only in debug mode

- src/main/java/io/percy/appium/providers/AppAutomate.java
- src/test/java/io/percy/appium/providers/AppAutomateTest.java
Changes:
- Fixed a null ref exception for case when bstack exec failed for percyScreenshotBegin, we try to read from null result to get DeviceName
> Fixed a NullRef exception

- src/main/java/io/percy/appium/lib/IgnoreRegion.java
- src/test/java/io/percy/appium/lib/IgnoreRegionTest.java
- src/test/java/io/percy/appium/providers/GenericProviderTest.java
Adding constructor for ignore region
> Adding constructor for ignore region

- package.json
- src/main/java/io/percy/appium/AppPercy.java
- src/main/java/io/percy/appium/lib/CliWrapper.java
- src/main/java/io/percy/appium/providers/AppAutomate.java
- src/main/java/io/percy/appium/providers/GenericProvider.java
- src/test/java/io/percy/appium/checkstyles.xml
- src/test/java/io/percy/appium/providers/AppAutomateTest.java
- yarn.lock
- Min cli version should be 1.25.0
- Appium version should be >=1.19 for full-page SS
> Add CLI and appiumVersion check

- src/main/java/io/percy/appium/metadata/IosMetadata.java
- src/test/java/io/percy/appium/metadata/IosMetadataTest.java
- Fixing wrong device height for ios devices.
> fixing device height for ios device

- src/main/java/io/percy/appium/PercyOnAutomate.java
- src/main/java/io/percy/appium/lib/CliWrapper.java
- src/main/java/io/percy/appium/lib/IgnoreRegion.java
- src/main/java/io/percy/appium/lib/Region.java
- src/main/java/io/percy/appium/lib/ScreenshotOptions.java
- src/main/java/io/percy/appium/providers/GenericProvider.java
- src/test/java/io/percy/appium/providers/GenericProviderTest.java
Allow passing consider region elements similar to API
> Add consider region support

- README.md
- package.json
- src/main/java/io/percy/appium/lib/CliWrapper.java
Update Java readme and minimum versions for POA
> Update Java readme and versions for POA

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> Release 2.0.1- beta.2

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> :bookmark: Release v2.0.0

- README.md
- src/main/java/io/percy/appium/lib/ScreenshotOptions.java
- src/main/java/io/percy/appium/providers/AppAutomate.java
- src/test/java/io/percy/appium/providers/AppAutomateTest.java
Adding 2 new options:
topScrollviewOffset
bottomScrollviewOffset
> Add scrollviewOffset options

- src/main/java/io/percy/appium/PercyOnAutomate.java
- src/main/java/io/percy/appium/metadata/DriverMetadata.java
- src/test/java/io/percy/appium/PercyOnAutomateTest.java
- src/test/java/io/percy/appium/metadata/DriverMetadataTest.java
Adding Caching for PoA Commands - `PercyScreesnhot`
> Adding Caching for PoA Commands

- pom.xml
- src/main/java/io/percy/appium/Environment.java
:bookmark: release v2.0.3-beta.0
> :bookmark: release v2.0.3-beta.0

- src/main/java/io/percy/appium/AppPercy.java
- src/main/java/io/percy/appium/Environment.java
- src/main/java/io/percy/appium/lib/CliWrapper.java
- src/test/java/io/percy/appium/EnvironmentTest.java
Sending failed event logs to cli
> Sending failed event logs to cli

- README.md
- pom.xml
- src/main/java/io/percy/appium/Environment.java
> :bookmark: release v2.0.3

- README.md
- src/main/java/io/percy/appium/lib/ScreenshotOptions.java
- src/main/java/io/percy/appium/metadata/AndroidMetadata.java
- src/main/java/io/percy/appium/metadata/IosMetadata.java
- src/main/java/io/percy/appium/metadata/Metadata.java
- src/main/java/io/percy/appium/providers/GenericProvider.java
- src/test/java/io/percy/appium/lib/ScreenshotOptionsTest.java
- src/test/java/io/percy/appium/metadata/IosMetadataTest.java
- src/test/java/io/percy/appium/providers/GenericProviderTest.java
Adding support for Appium Client  v8 and v9
This can cause minor compatibility issue while using `getIgnoreRegionAppiumElements`
> Adding support for Appium Client v8 and v9

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> release 2.1.0-beta.0

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> release 2.1.0

- src/main/java/io/percy/appium/AppPercy.java
- src/main/java/io/percy/appium/IPercy.java
- src/main/java/io/percy/appium/Percy.java
- src/main/java/io/percy/appium/PercyOnAutomate.java
- src/main/java/io/percy/appium/lib/CliWrapper.java
- src/main/java/io/percy/appium/lib/ScreenshotOptions.java
- src/main/java/io/percy/appium/providers/AppAutomate.java
- src/main/java/io/percy/appium/providers/GenericProvider.java
- src/test/java/io/percy/appium/PercyOnAutomateTest.java
- src/test/java/io/percy/appium/lib/ScreenshotOptionsTest.java
- src/test/java/io/percy/appium/providers/AppAutomateTest.java
- Adding Sync call to screenshot
- 600 sec timeout.
sync cli reponse
> Adding Sync call to app percy and POA

- README.md
- pom.xml
- src/main/java/io/percy/appium/Environment.java
:bookmark: release-v2.1.1-beta.0 and readme update
> :bookmark: release-v2.1.1-beta.0

- pom.xml
- src/main/java/io/percy/appium/Environment.java
:bookmark: release-v2.1.1-beta.1
> :bookmark: release-v2.1.1-beta.1

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> :bookmark: release-v2.1.1

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> Releasing v2.1.2

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> Version bump to v2.1.3

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> releasing v2.1.4

- src/main/java/io/percy/appium/providers/GenericProvider.java
- src/test/java/io/percy/appium/providers/GenericProviderTest.java
fixing isValid function call bug and adding tests as well.
> fixing isValid function call bug

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> releasing v2.1.5

- README.md
- pom.xml
- src/main/java/io/percy/appium/Environment.java
> 🔖  Release v2.1.6

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
> Docs Url Update to browserstack url

- README.md
- pom.xml
- src/main/java/io/percy/appium/lib/ScreenshotOptions.java
- src/main/java/io/percy/appium/providers/AppAutomate.java
- src/test/java/io/percy/appium/lib/ScreenshotOptionsTest.java
- src/test/java/io/percy/appium/providers/AppAutomateTest.java
adding new params to support scroll speed and scroll percentage area for fullpage screenshot
https://browserstack.atlassian.net/browse/PAPP-480
> adding new params to support scroll speed and scroll percentage area for fullpage screenshot

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> releasing v2.1.8

- src/main/java/io/percy/appium/metadata/AndroidMetadata.java
- src/main/java/io/percy/appium/metadata/IosMetadata.java
- src/main/java/io/percy/appium/metadata/Metadata.java
- src/test/java/io/percy/appium/checkstyles.xml
- Fixed static driver causing platform name mismatch for devices
- Reduced duplication
> Fixed driver sharing due to static keyword

- src/main/java/io/percy/appium/lib/CliWrapper.java
- src/main/java/io/percy/appium/lib/ScreenshotOptions.java
- src/main/java/io/percy/appium/providers/GenericProvider.java
- src/test/java/io/percy/appium/lib/ScreenshotOptionsTest.java
> adding support for label

- pom.xml
- src/main/java/io/percy/appium/Environment.java
> release-v2.2.0
